# Generated by Django 6.0 on 2025-12-03 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='nota',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
